---
- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
    - name: Create user
      user:
        name: njike
        comment: tyler njike
    - name: Create directory
      file:
        path: /tmp/devop-ans
        owner: njike
        state: directory
        mode: "0777"
    - name: Create file
      file:
        path: /tmp/ansible-class
        owner: njike
        state: touch
        mode: "0600"
